import type { Metadata } from "next";
import "./globals.css";
import { BranchingProvider } from "@/lib/branching-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-white">
      <body className="antialiased h-full overflow-hidden bg-white text-zinc-900">
        <BranchingProvider>{children}</BranchingProvider>
      </body>
    </html>
  );
}
